
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
      image: 'bitnami/kafka:latest'
      ports:
        - '9092:9092'
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper

  config-server:
    build: .
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 10s
    networks:
      default:
        aliases:
          - "config-server"

  eureka-server:
    image: indiagator/eurekaserver-tcsjul23:0.2
    ports:
      - "8070:8070"
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 10s
    networks:
      default:
        aliases:
          - "eureka-server"

  analytics-service:
    image: indiagator/analyticsservice:forkafka7
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8099/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 10s
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      kafka:
        condition: service_started

  auth-service:
    image: indiagator/authservice:jan24prod1
    deploy:
      mode: replicated
      replicas: 2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8095/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 10s
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      kafka:
        condition: service_started

  gateway-server:
    image: indiagator/gatewayserver:swarm1
    hostname: gateway-server-host
    ports:
      - "8072:8072"
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8072/actuator/health" ]
      interval: 10s
      timeout: 12s
      retries: 3
      start_period: 10s
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      default:
        aliases:
          - "gateway-server"

  zipkin-server:
    image: 'openzipkin/zipkin'
    ports:
      - '9411:9411'




