
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/indiagator/code22-config-server-properties.git
          refresh-rate: 1
  zipkin:
    base-url: http://localhost:9411/

logging:
  level:
    org:
      springframework: DEBUG

zipkin:
  baseUrl: http://localhost:9411

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: refresh






